-- H2-only authentication fixture. PostgreSQL migrations are verified separately by MigrationIT.
-- Executed only in AuthenticationFlowIT's dedicated in-memory database; never in the application.
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('REQUESTER', 'TECHNICIAN', 'ADMINISTRATOR')),
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE', 'DISABLED')),
    security_version BIGINT NOT NULL DEFAULT 0 CHECK (security_version >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
