-- H2-only authentication fixture. PostgreSQL migrations are verified separately by MigrationIT.
-- Executed only in the dedicated in-memory databases of AuthenticationFlowIT and
-- RegistrationFlowIT, one database each; never in the application.
-- It drops and recreates `users` before every test method, so each test starts from an
-- empty account table with a reset identity - which is what lets both classes create the
-- same usernames, and lets the registration tests assert on exactly one row.
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('REQUESTER', 'TECHNICIAN', 'ADMINISTRATOR')),
    account_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (account_status IN ('ACTIVE', 'DISABLED')),
    security_version BIGINT NOT NULL DEFAULT 0 CHECK (security_version >= 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
