-- Isolated H2 technician fixture matching V23's technician tables. Native tests verify Flyway.
CREATE TABLE technician_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    availability_status VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_technician_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_technician_profiles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_technician_profiles_availability CHECK (availability_status IN ('AVAILABLE', 'BUSY', 'ON_LEAVE')),
    CONSTRAINT chk_technician_profiles_version CHECK (version >= 0)
);

CREATE TABLE technician_skills (
    technician_profile_id BIGINT NOT NULL,
    category VARCHAR(20) NOT NULL,
    PRIMARY KEY (technician_profile_id, category),
    CONSTRAINT fk_technician_skills_profile FOREIGN KEY (technician_profile_id) REFERENCES technician_profiles(id),
    CONSTRAINT chk_technician_skills_category CHECK (category IN ('ELECTRICAL', 'PLUMBING', 'HVAC', 'BUILDING', 'OTHER'))
);

CREATE TABLE technician_service_areas (
    technician_profile_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    PRIMARY KEY (technician_profile_id, location_id),
    CONSTRAINT fk_technician_service_areas_profile FOREIGN KEY (technician_profile_id) REFERENCES technician_profiles(id),
    CONSTRAINT fk_technician_service_areas_location FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE INDEX idx_technician_skills_category ON technician_skills(category, technician_profile_id);
CREATE INDEX idx_technician_service_areas_location ON technician_service_areas(location_id, technician_profile_id);
