-- S3-B-03: apply in the team's reserved V11 slot, before V12 on a fresh/ordered upgrade.
-- technician_id is users.id (the same identity used by C's work orders), not profile id.
CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES maintenance_requests(id),
    technician_id BIGINT NOT NULL REFERENCES users(id),
    assigned_by_user_id BIGINT NOT NULL REFERENCES users(id),
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    deactivated_by_user_id BIGINT REFERENCES users(id),
    deactivated_at TIMESTAMP WITH TIME ZONE,
    deactivation_reason VARCHAR(500),
    CONSTRAINT chk_assignments_version CHECK (version >= 0),
    CONSTRAINT chk_assignments_reason CHECK (reason IS NULL OR LENGTH(TRIM(reason)) > 0),
    CONSTRAINT chk_assignments_deactivation CHECK (
        (active AND deactivated_by_user_id IS NULL AND deactivated_at IS NULL AND deactivation_reason IS NULL)
        OR (NOT active AND deactivated_by_user_id IS NOT NULL AND deactivated_at IS NOT NULL
            AND deactivation_reason IS NOT NULL AND LENGTH(TRIM(deactivation_reason)) > 0)
    )
);

-- A pre-insert check alone is insufficient: this index arbitrates concurrent administrators.
CREATE UNIQUE INDEX uk_assignments_active_request ON assignments(request_id) WHERE active;
CREATE INDEX idx_assignments_technician_active ON assignments(technician_id, active);
CREATE INDEX idx_assignments_request_history ON assignments(request_id, assigned_at, id);
