CREATE TABLE facilities (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            location_id BIGINT NOT NULL,
                            name VARCHAR(120) NOT NULL,
                            description VARCHAR(500),
                            status VARCHAR(30) NOT NULL DEFAULT 'OPERATIONAL',
                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT fk_facilities_location
                                FOREIGN KEY (location_id)
                                    REFERENCES locations(id),

                            CONSTRAINT chk_facilities_name
                                CHECK (
                                    char_length(name) BETWEEN 1 AND 120
                                        AND name = btrim(name)
                                    ),

                            CONSTRAINT chk_facilities_status
                                CHECK (
                                    status IN (
                                               'OPERATIONAL',
                                               'UNDER_MAINTENANCE',
                                               'OUT_OF_SERVICE'
                                        )
                                    )
);

CREATE INDEX idx_facilities_location
    ON facilities(location_id);

CREATE INDEX idx_facilities_status
    ON facilities(status);
