-- ============================================================
-- V14 - SmartFix Sprint 3
-- Category E: In-app notifications
-- ============================================================

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    recipient_id BIGINT NOT NULL,

    event_type VARCHAR(80) NOT NULL,

    dedup_key VARCHAR(200) NOT NULL,

    title VARCHAR(150) NOT NULL,

    message VARCHAR(1000) NOT NULL,

    reference_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    read_at TIMESTAMPTZ,

    CONSTRAINT fk_notifications_recipient
        FOREIGN KEY (recipient_id)
        REFERENCES users(id),

    CONSTRAINT uk_notifications_dedup_key
        UNIQUE (dedup_key),

    CONSTRAINT chk_notifications_event_type
        CHECK (char_length(event_type) BETWEEN 1 AND 80),

    CONSTRAINT chk_notifications_title
        CHECK (char_length(title) BETWEEN 1 AND 150),

    CONSTRAINT chk_notifications_message
        CHECK (char_length(message) BETWEEN 1 AND 1000),

    CONSTRAINT chk_notifications_read_time
        CHECK (read_at IS NULL OR read_at >= created_at)
);

CREATE INDEX idx_notifications_recipient_created
    ON notifications (recipient_id, created_at DESC);

CREATE INDEX idx_notifications_recipient_unread
    ON notifications (recipient_id)
    WHERE read_at IS NULL;