-- V16 - SmartFix Sprint 3
-- Category D: Announcements

CREATE TABLE announcements (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               title VARCHAR(150) NOT NULL,

                               content VARCHAR(4000) NOT NULL,

                               status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

                               valid_from TIMESTAMPTZ NOT NULL,

                               valid_to TIMESTAMPTZ,

                               created_by BIGINT NOT NULL,

                               created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                               published_at TIMESTAMPTZ,

                               withdrawn_at TIMESTAMPTZ,

                               CONSTRAINT fk_announcements_created_by
                                   FOREIGN KEY (created_by)
                                       REFERENCES users(id),

                               CONSTRAINT chk_announcements_status
                                   CHECK (status IN ('DRAFT', 'PUBLISHED', 'WITHDRAWN')),

                               CONSTRAINT chk_announcements_title
                                   CHECK (
                                       char_length(btrim(title)) BETWEEN 1 AND 150
                                       ),

                               CONSTRAINT chk_announcements_content
                                   CHECK (
                                       char_length(btrim(content)) BETWEEN 1 AND 4000
                                       ),

                               CONSTRAINT chk_announcements_valid_period
                                   CHECK (
                                       valid_to IS NULL OR valid_to > valid_from
                                       )
);

CREATE INDEX idx_announcements_status_validity
    ON announcements (
                      status,
                      valid_from,
                      valid_to
        );

CREATE INDEX idx_announcements_created_at
    ON announcements (
                      created_at DESC
        );
