-- Sprint 3 community board, part 1 of 2: the two content tables.
--
-- The cycle
-- ---------
-- community_questions.accepted_answer_id points at community_answers, and
-- community_answers.question_id points back at community_questions. Neither table can
-- therefore be created with both foreign keys already in place. The split is:
--
--   V17 (this file)  create both tables. community_answers.question_id gets its foreign
--                    key immediately, because community_questions exists by then.
--                    community_questions.accepted_answer_id is created as a plain
--                    column, deliberately WITHOUT a foreign key.
--   V18              ALTER TABLE ... ADD CONSTRAINT closes the cycle, in one statement,
--                    once both tables exist.
--
-- Why the accepted answer needs a composite foreign key rather than a simple one
-- -----------------------------------------------------------------------------
-- A single-column foreign key accepted_answer_id -> community_answers(id) would only
-- prove the answer exists. It would not prove the answer belongs to *this* question,
-- so a question could be marked solved by an unrelated question's answer. The pair
-- (accepted_answer_id, id) -> community_answers (id, question_id) states the stronger
-- rule and the database enforces it.
--
-- MATCH SIMPLE (the default) is what makes the nullable case work: when any column of
-- the referencing list is NULL, the constraint is not checked, so an open question
-- with accepted_answer_id IS NULL passes. NULLs are also distinct in a UNIQUE
-- constraint, so uk_community_questions_id_accepted_answer below does not stop
-- thousands of open questions coexisting.
--
-- No ON DELETE CASCADE anywhere, on purpose
-- ----------------------------------------
-- Hiding and withdrawing are logical states, not deletions: a hidden question keeps its
-- answers, and no convention in this schema physically deletes user content. A cascade
-- here would silently destroy replies the moment someone hid a question.

CREATE TABLE community_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title VARCHAR(150) NOT NULL,
    body VARCHAR(4000) NOT NULL,
    category VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    accepted_answer_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_community_questions_author FOREIGN KEY(author_id) REFERENCES users(id),
    CONSTRAINT uk_community_questions_id_accepted_answer UNIQUE(id, accepted_answer_id),
    CONSTRAINT chk_community_questions_category
        CHECK(category IN ('HARDWARE','SOFTWARE','NETWORK','PERIPHERAL','OTHER')),
    CONSTRAINT chk_community_questions_status
        CHECK(status IN ('VISIBLE','HIDDEN','WITHDRAWN')),
    -- The same bounds the command DTO and the entity enforce, so a value that reaches
    -- the table by any other route still cannot be stored out of range. btrim() is
    -- spelled out because the entity trims before it stores: Java's trim() removes
    -- every character <= U+0020, which is a superset of what btrim() removes by
    -- default, so a trimmed value always satisfies this.
    CONSTRAINT chk_community_questions_title
        CHECK(title = btrim(title) AND char_length(title) BETWEEN 3 AND 150),
    CONSTRAINT chk_community_questions_body
        CHECK(body = btrim(body) AND char_length(body) BETWEEN 10 AND 4000)
);
CREATE INDEX idx_community_questions_status_created ON community_questions(status, created_at DESC, id DESC);
CREATE INDEX idx_community_questions_author ON community_questions(author_id, created_at DESC);

CREATE TABLE community_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    body VARCHAR(4000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_community_answers_question FOREIGN KEY(question_id) REFERENCES community_questions(id),
    CONSTRAINT fk_community_answers_author FOREIGN KEY(author_id) REFERENCES users(id),
    -- Not redundant with the primary key. This is the unique key the composite foreign
    -- key in V18 references: PostgreSQL requires the referenced column list to carry a
    -- unique constraint, and (id, question_id) is the pair that makes "the accepted
    -- answer belongs to this question" expressible as a single constraint.
    CONSTRAINT uk_community_answers_id_question UNIQUE(id, question_id),
    CONSTRAINT chk_community_answers_status
        CHECK(status IN ('VISIBLE','HIDDEN','WITHDRAWN')),
    CONSTRAINT chk_community_answers_body
        CHECK(body = btrim(body) AND char_length(body) BETWEEN 10 AND 4000)
);
CREATE INDEX idx_community_answers_question_created ON community_answers(question_id, created_at, id);
CREATE INDEX idx_community_answers_author ON community_answers(author_id, created_at DESC);
