-- Sprint 3 community board, part 3: reports.
--
-- A report points at exactly one piece of content
-- ----------------------------------------------
-- One table serves both kinds of report, and chk_community_reports_target makes
-- "exactly one target" a rule the database enforces rather than one the service
-- remembers: (question_id IS NOT NULL) <> (answer_id IS NOT NULL). A row with both
-- set would name two pieces of content and no reader could say which one was
-- reported; a row with neither would name nothing at all. Both are refused here, at
-- the only layer that cannot be bypassed.
--
-- Reporting the same content twice
-- --------------------------------
-- uk_community_reports_question and uk_community_reports_answer make one report per
-- reporter per target a permanent rule: reporting something is a statement, and a
-- second identical statement adds no information for a moderator to act on. The
-- consequence - a reporter cannot report the same content again after their first
-- report has been handled - is deliberate and is recorded as a decision in
-- docs/sprint3/UserA_Community_Implementation_Contract_CN.md, together with the
-- one-line index change that would be needed to allow it.
--
-- The indexes are partial (WHERE ... IS NOT NULL) rather than plain UNIQUE
-- constraints. Both enforce the same rule, because NULLs are distinct in a unique
-- index and a question report never collides with an answer report in either; the
-- partial form is the one that says out loud which rows it is about, and it does not
-- index the half of the table the constraint says nothing about.
--
-- The service checks first, and this is still needed
-- --------------------------------------------------
-- CommunityModerationService refuses an obvious duplicate with a sentence a person
-- can read, and that check runs before the insert. It is a read followed by a write
-- and the two are not atomic with respect to each other, so two simultaneous reports
-- of the same target can both pass it. The unique indexes above are what makes the
-- outcome of that race one row plus one refusal rather than two rows; the refusal is
-- the same message, produced by the same exception.
--
-- No ON DELETE CASCADE, for the reason V17 gives
-- ----------------------------------------------
-- A report is evidence about content. A cascade would delete the evidence the moment
-- somebody hid the thing it is evidence about, which is exactly backwards: hiding a
-- question keeps its answers (V17) and hiding either keeps the reports that led to
-- it. Nothing in this schema physically deletes user content or moderation history.

CREATE TABLE community_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT,
    answer_id BIGINT,
    reporter_id BIGINT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    detail VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    handled_by_user_id BIGINT,
    handled_at TIMESTAMPTZ,
    resolution_note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_community_reports_question FOREIGN KEY(question_id) REFERENCES community_questions(id),
    CONSTRAINT fk_community_reports_answer FOREIGN KEY(answer_id) REFERENCES community_answers(id),
    CONSTRAINT fk_community_reports_reporter FOREIGN KEY(reporter_id) REFERENCES users(id),
    CONSTRAINT fk_community_reports_handler FOREIGN KEY(handled_by_user_id) REFERENCES users(id),
    -- Exactly one target. Written as an inequality of two conditions, which is what
    -- makes "both set" and "neither set" the same failure, and is why the service
    -- never has to defend against a report of two things at once.
    CONSTRAINT chk_community_reports_target
        CHECK((question_id IS NOT NULL) <> (answer_id IS NOT NULL)),
    CONSTRAINT chk_community_reports_reason
        CHECK(reason IN ('SPAM','ABUSIVE','OFF_TOPIC','DUPLICATE','OTHER')),
    CONSTRAINT chk_community_reports_status
        CHECK(status IN ('OPEN','ACTIONED','DISMISSED')),
    -- A settled report always names who settled it and when, and an open one never
    -- pretends to. Tying the two columns to each other rather than to a default is
    -- what stops a row from being half-decided - which a queue that sorts by status
    -- and displays the handler would show as a report handled by nobody.
    CONSTRAINT chk_community_reports_handled
        CHECK((status = 'OPEN') = (handled_at IS NULL)),
    -- The same normalization the entity performs before it stores, so a value that
    -- reaches this table by any other route cannot be stored with surrounding
    -- whitespace that the queue would then display.
    CONSTRAINT chk_community_reports_detail
        CHECK(detail IS NULL OR detail = btrim(detail) AND char_length(detail) BETWEEN 1 AND 500),
    CONSTRAINT chk_community_reports_note
        CHECK(resolution_note IS NULL OR (resolution_note = btrim(resolution_note)
                                          AND char_length(resolution_note) BETWEEN 1 AND 500))
);

-- The queue's own index. Oldest first, because the moderator's question is "what has
-- been waiting longest", and the id is appended for the reason every other index in
-- V17 carries one: two reports can share a timestamp, and without a tie-breaker the
-- database may order them differently on each page, showing one row twice and another
-- never.
CREATE INDEX idx_community_reports_queue ON community_reports(status, created_at, id);

CREATE UNIQUE INDEX uk_community_reports_question
    ON community_reports(reporter_id, question_id) WHERE question_id IS NOT NULL;

CREATE UNIQUE INDEX uk_community_reports_answer
    ON community_reports(reporter_id, answer_id) WHERE answer_id IS NOT NULL;
