-- Durable moderation audit. Records commit and roll back with their business action.
CREATE TABLE audit_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL REFERENCES users(id),
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_audit_entries_target CHECK(target_type IN ('QUESTION','ANSWER','REPORT'))
);
CREATE INDEX idx_audit_entries_time ON audit_entries(occurred_at DESC, id DESC);
CREATE INDEX idx_audit_entries_target ON audit_entries(target_type, target_id, occurred_at DESC);
