-- Current feature branch has already published V22 without the main V10/V11 modules.
-- Add their existing schemas at the next version; never change published history.
-- Existing main schemas are retained when these tables already exist.
CREATE TABLE IF NOT EXISTS technician_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    availability_status VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_technician_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_technician_profiles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_technician_profiles_availability CHECK (availability_status IN ('AVAILABLE', 'BUSY', 'ON_LEAVE')),
    CONSTRAINT chk_technician_profiles_version CHECK (version >= 0)
);

CREATE TABLE IF NOT EXISTS technician_skills (
    technician_profile_id BIGINT NOT NULL,
    category VARCHAR(20) NOT NULL,
    PRIMARY KEY (technician_profile_id, category),
    CONSTRAINT fk_technician_skills_profile FOREIGN KEY (technician_profile_id) REFERENCES technician_profiles(id),
    CONSTRAINT chk_technician_skills_category CHECK (category IN ('ELECTRICAL', 'PLUMBING', 'HVAC', 'BUILDING', 'OTHER'))
);

CREATE TABLE IF NOT EXISTS technician_service_areas (
    technician_profile_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    PRIMARY KEY (technician_profile_id, location_id),
    CONSTRAINT fk_technician_service_areas_profile FOREIGN KEY (technician_profile_id) REFERENCES technician_profiles(id),
    CONSTRAINT fk_technician_service_areas_location FOREIGN KEY (location_id) REFERENCES locations(id)
);

CREATE INDEX IF NOT EXISTS idx_technician_skills_category ON technician_skills(category, technician_profile_id);
CREATE INDEX IF NOT EXISTS idx_technician_service_areas_location ON technician_service_areas(location_id, technician_profile_id);

CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES maintenance_requests(id),
    technician_id BIGINT NOT NULL REFERENCES users(id),
    assigned_by_user_id BIGINT NOT NULL REFERENCES users(id),
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    deactivated_by_user_id BIGINT REFERENCES users(id),
    deactivated_at TIMESTAMP WITH TIME ZONE,
    deactivation_reason VARCHAR(500),
    CONSTRAINT chk_assignments_version CHECK (version >= 0),
    CONSTRAINT chk_assignments_reason CHECK (reason IS NULL OR LENGTH(TRIM(reason)) > 0),
    CONSTRAINT chk_assignments_deactivation CHECK (
        (active AND deactivated_by_user_id IS NULL AND deactivated_at IS NULL AND deactivation_reason IS NULL)
        OR (NOT active AND deactivated_by_user_id IS NOT NULL AND deactivated_at IS NOT NULL
            AND deactivation_reason IS NOT NULL AND LENGTH(TRIM(deactivation_reason)) > 0)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_assignments_active_request ON assignments(request_id) WHERE active;
CREATE INDEX IF NOT EXISTS idx_assignments_technician_active ON assignments(technician_id, active);
CREATE INDEX IF NOT EXISTS idx_assignments_request_history ON assignments(request_id, assigned_at, id);
