-- ============================================================
-- V2 - SmartFix Sprint 2, work category A (accounts and roles)
-- ------------------------------------------------------------
-- Creates the `users` table: one row per system account.
--
-- Design notes:
--  * The schema is owned by Flyway only (`ddl-auto: none` in
--    application.yml). This file is the single definition of the table.
--  * `role` and `account_status` store the enum NAME, never an ordinal,
--    so rows stay readable and reordering an enum cannot corrupt data.
--  * `security_version` is bumped whenever the role or the status really
--    changes. Category B compares it against the value captured at login
--    and invalidates any older session (plan section 12.1, AC09).
--  * `TIMESTAMPTZ` + `Instant` in Java: the instant is stored in UTC and
--    rendered in Asia/Singapore (plan section 10.0).
--  * No account and no password is seeded here. The first administrator is
--    created by the environment-driven, idempotent bootstrap path
--    (BootstrapAdminInitializer -> UserBootstrapService -> UserService).
--    A default credential must never live in a migration.
--
-- PostgreSQL only: Flyway runs against real PostgreSQL. The H2 test
-- profile keeps `flyway.enabled: false` (plan section 21.4).
-- ============================================================

CREATE TABLE users (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(50)  NOT NULL,
    display_name     VARCHAR(100) NOT NULL,
    password_hash    VARCHAR(100) NOT NULL,
    role             VARCHAR(20)  NOT NULL,
    account_status   VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    security_version BIGINT       NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Usernames are stored trimmed and lower-cased, so a plain unique
    -- constraint is enough to stop "Alice" / "alice" becoming two accounts.
    CONSTRAINT uk_users_username UNIQUE (username),

    -- Mirrors User.USERNAME_PATTERN. The service normalizes and validates
    -- first; this constraint is the last line of defence.
    CONSTRAINT chk_users_username
        CHECK (username ~ '^[a-z0-9._-]{3,50}$'),

    -- The three officially approved roles only. No FACILITY_OFFICER.
    CONSTRAINT chk_users_role
        CHECK (role IN ('REQUESTER', 'TECHNICIAN', 'ADMINISTRATOR')),

    CONSTRAINT chk_users_account_status
        CHECK (account_status IN ('ACTIVE', 'DISABLED')),

    CONSTRAINT chk_users_security_version
        CHECK (security_version >= 0)
);
