CREATE TABLE locations (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           location_code VARCHAR(50) NOT NULL,
                           building VARCHAR(100),
                           floor VARCHAR(20),
                           room VARCHAR(50),
                           display_name VARCHAR(150) NOT NULL,
                           active BOOLEAN NOT NULL DEFAULT TRUE,

                           CONSTRAINT uk_locations_location_code UNIQUE (location_code)
);

CREATE INDEX idx_locations_active
    ON locations (active);
