-- ============================================================
-- V4 - SmartFix Sprint 2, work category C (request submission)
-- ------------------------------------------------------------
-- Creates the maintenance-request aggregate root and the
-- concurrency-safe, year-scoped ticket counter.
--
-- Prerequisites:
--   V2__create_users.sql       (users)
--   V3__create_locations.sql   (locations, owned by category D)
--
-- Request status history is intentionally not created here. The
-- Sprint 2 migration plan reserves V5 for attachments and V6 for
-- request_status_history. V6 must not be applied before V5 has been
-- registered/merged, otherwise existing developer databases would
-- need out-of-order Flyway migrations.
-- ============================================================

CREATE TABLE maintenance_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number  VARCHAR(20)   NOT NULL,
    requester_id   BIGINT        NOT NULL,
    location_id    BIGINT        NOT NULL,
    title          VARCHAR(120)  NOT NULL,
    description    VARCHAR(2000) NOT NULL,
    category       VARCHAR(30)   NOT NULL,
    urgency_level  VARCHAR(20)   NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'SUBMITTED',
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_maintenance_requests_ticket_number UNIQUE (ticket_number),
    CONSTRAINT fk_maintenance_requests_requester
        FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT fk_maintenance_requests_location
        FOREIGN KEY (location_id) REFERENCES locations (id),
    CONSTRAINT chk_maintenance_requests_ticket_number
        CHECK (ticket_number ~ '^SF-[0-9]{4}-[0-9]{6}$'),
    CONSTRAINT chk_maintenance_requests_title
        CHECK (char_length(title) BETWEEN 1 AND 120 AND title = btrim(title)),
    CONSTRAINT chk_maintenance_requests_description
        CHECK (char_length(description) BETWEEN 1 AND 2000 AND description = btrim(description)),
    CONSTRAINT chk_maintenance_requests_category
        CHECK (category IN ('ELECTRICAL', 'PLUMBING', 'HVAC', 'BUILDING', 'OTHER')),
    CONSTRAINT chk_maintenance_requests_urgency_level
        CHECK (urgency_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_maintenance_requests_status
        CHECK (status IN ('SUBMITTED'))
);

-- One row per Singapore calendar year. The generator first inserts
-- the row if absent (ON CONFLICT DO NOTHING), then locks it with
-- SELECT ... FOR UPDATE before consuming next_value.
CREATE TABLE request_ticket_sequences (
    ticket_year INTEGER PRIMARY KEY,
    next_value  BIGINT NOT NULL DEFAULT 1,

    CONSTRAINT chk_request_ticket_sequences_next_value
        CHECK (next_value BETWEEN 1 AND 1000000)
);
