============================================================
V5 - SmartFix Sprint 2, work category E (attachments)
============================================================

CREATE TABLE request_attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id        BIGINT       NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename   VARCHAR(255) NOT NULL,
    content_type      VARCHAR(100) NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_request_attachments_stored_filename
        UNIQUE (stored_filename),

    CONSTRAINT fk_request_attachments_request
        FOREIGN KEY (request_id)
        REFERENCES maintenance_requests (id),

    CONSTRAINT chk_request_attachments_size
        CHECK (size_bytes > 0),

    CONSTRAINT chk_request_attachments_content_type
        CHECK (content_type IN ('image/png', 'image/jpeg'))
);

CREATE INDEX idx_request_attachments_request_id
    ON request_attachments (request_id);