CREATE TABLE request_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    changed_by_user_id BIGINT NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment VARCHAR(500),
    CONSTRAINT fk_request_status_history_request FOREIGN KEY (request_id) REFERENCES maintenance_requests(id),
    CONSTRAINT fk_request_status_history_actor FOREIGN KEY (changed_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_request_status_history_from CHECK (from_status IS NULL OR from_status IN
        ('SUBMITTED','UNDER_REVIEW','ASSIGNED','IN_PROGRESS','RESOLVED','CONFIRMED','REOPENED','CLOSED','REJECTED','CANCELLED')),
    CONSTRAINT chk_request_status_history_to CHECK (to_status IN
        ('SUBMITTED','UNDER_REVIEW','ASSIGNED','IN_PROGRESS','RESOLVED','CONFIRMED','REOPENED','CLOSED','REJECTED','CANCELLED')),
    CONSTRAINT chk_request_status_history_change CHECK
        ((from_status IS NULL AND to_status = 'SUBMITTED') OR (from_status IS NOT NULL AND from_status <> to_status))
);
CREATE INDEX idx_request_status_history_timeline ON request_status_history(request_id, changed_at, id);
CREATE UNIQUE INDEX uk_request_status_history_initial ON request_status_history(request_id) WHERE from_status IS NULL;
