CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
    version BIGINT NOT NULL DEFAULT 0,
    resolution_note VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uk_work_orders_request UNIQUE(request_id),
    CONSTRAINT fk_work_orders_request FOREIGN KEY(request_id) REFERENCES maintenance_requests(id),
    CONSTRAINT fk_work_orders_technician FOREIGN KEY(technician_id) REFERENCES users(id),
    CONSTRAINT chk_work_orders_status CHECK(status IN ('CREATED','IN_PROGRESS','ON_HOLD','COMPLETED','REOPENED','CLOSED'))
);
CREATE INDEX idx_work_orders_technician_status ON work_orders(technician_id, status);
CREATE TABLE repair_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL,
    technician_id BIGINT NOT NULL,
    diagnosis VARCHAR(2000) NOT NULL,
    action_taken VARCHAR(2000) NOT NULL,
    materials_used VARCHAR(1000),
    minutes_spent INTEGER NOT NULL,
    evidence_attachment_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_repair_records_order FOREIGN KEY(work_order_id) REFERENCES work_orders(id),
    CONSTRAINT fk_repair_records_technician FOREIGN KEY(technician_id) REFERENCES users(id),
    CONSTRAINT fk_repair_records_evidence FOREIGN KEY(evidence_attachment_id) REFERENCES request_attachments(id),
    CONSTRAINT chk_repair_records_minutes CHECK(minutes_spent > 0),
    CONSTRAINT chk_repair_records_diagnosis CHECK(char_length(btrim(diagnosis)) BETWEEN 1 AND 2000),
    CONSTRAINT chk_repair_records_action CHECK(char_length(btrim(action_taken)) BETWEEN 1 AND 2000)
);
CREATE INDEX idx_repair_records_order_created ON repair_records(work_order_id, created_at, id);
