CREATE TABLE request_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    comment VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_request_feedback_request UNIQUE(request_id),
    CONSTRAINT fk_request_feedback_request FOREIGN KEY(request_id) REFERENCES maintenance_requests(id),
    CONSTRAINT fk_request_feedback_requester FOREIGN KEY(requester_id) REFERENCES users(id),
    CONSTRAINT chk_request_feedback_rating CHECK(rating BETWEEN 1 AND 5)
);
